# Replacements are done before splitting the text into sentences


replacements = [
  ["һ.б.", "һәм башкалар"],
  ["Һ.б.", "һәм башкалар"],
  ["һ.б", "һәм башкалар"],
  ["һ. б.", "һәм башкалар"],
  ["б.э.к.", "безнең эрага кадәр"],
  ["б. э. к.", "безнең эрага кадәр"],
  ["б. э.к.", "безнең эрага кадәр"],
  ["б.э.", "безнең эрага"],
  ["б. э.", "безнең эрага"],
  [", мәс.", ", мәсәлән"],
  ["а.х.", "авыл хуҗалыгының"],
  [" ис.", " исемендәге"],
  [" ур.", " урамы"],
  ["б. ш.", "башка шундыйлар"],
  ["ш.о", "шәһәр округы"],
  ["ш.т.б", "шәһәр тибындагы бистә"],
  [" ш.", " шәһәре"],
  [" а.", " авылы"],
  ["\n", ""],
  ["‘", "'"],     # U+2018 => apostrophe
  ["’", "'"],     # U+2019 => apostrophe
  #["«", "\""],     
  #["»", "\""],  
  #["­", ""],       # U+00AD => empty string
  #[" ", " "],     # U+00A0 => whitespace
  #[" ", " "],     # U+2002 => whitespace
  #[" ", " "],     # U+202F => whitespace
  #["‑", "-"],     # U+2011 => hyphen
  #["–", "—"],     # U+2013 => U+2014
  #["―", "—"],     # U+2015 => U+2014
  #["−", "—"],     # U+2212 => U+2014
  #[" - ", " — "], # hyphen => U+2014, when between whitespaces
]
abbreviation_patterns = [
  # Л. Баталов
  #"[А-ЯӘҖҢӨҮҺ]\\.",
  # ВХУТЕМАСка В.К.Тимофеевта
  #"[А-ЯӘҖҢӨҮҺ][а-яәҗңөүһ]\\.",
  # БССР
  #"[А-ЯӘҖҢӨҮҺ]{2,}",
  # Эшмәкәрләр и.с.
  #"[а-яәҗңөүһ]\\.[А-ЯӘҖҢӨҮҺа-яәҗңөүһ]",
  # Хулга е.
  #"\\s[а-яәҗңөүһ]\\.",
  # пр.-тюркск.
  #"\\.\\-",
  # 
  #"\\(.*?\\)"
]


min_trimmed_length = 3
min_word_count = 2
max_word_count = 14
min_characters = 2
may_end_with_colon = true
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = true
#allowed_symbols_regex = "[0123456789A-Za-zА-ЯӘҖҢӨҮҺа-яәҗңөүһ'\\s,.\\-‑?!—­‐–―−„“\"«»]"
#а́ — е́ ы́  и́ 
#disallowed_symbols = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 
#'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z',
# '<', '>', '+', '*']
broken_whitespace =  ["  ", " ,", " .", " ?", " !", " ;"]
matching_symbols = [
  ["„", "“"],
  ["(", ")"],
  ["«", "»"],
]
#46385
#47141

#46393
#45665

#49588

#о́и́
other_patterns = [
    # Some Russian stopwords not present in Tatar language
    # не, в, на, с, что, к, по, у, из, был, то, которого, весь, и
    #"(\\s?\\s^[не|в|на|с|что|к|по|у|из|был|то|которого|весь|и|это])"
    "(\\sне\\s|\\sВ\\s|\\sв\\s|\\sна\\s|\\sс\\s|\\sчто\\s|\\sк\\s|\\sпо\\s|\\sу\\s|\\sиз\\s|\\sбыл\\s|\\sто\\s|\\sкоторого\\s|\\sвесь\\s|\\sи\\s|\\sэто\\s)",
    # City was found in this year
    "(елда\\sнигезләнгән)",
    "(www)",
    "[MCLXVI]\\s"
    # russianWords = [ 
    #            ' быть ',' я ',' он ',' а ', 
    #            ' это ',' так ',' то ',' этот ', 
    #            ' они ',' мы ',' но ', 
    #            ' она ',' который ', 
    #            ' вы ',' так ', ' в ']
    
]



